"""ilk sema

Revision ID: 0001
Revises: 
Create Date: 2026-08-08 14:32:32.189737
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Şemayı ileri al."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('legal_name', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=False),
    sa.Column('legacy_domains', sa.JSON(), nullable=True),
    sa.Column('bddk_status', sa.Text(), nullable=False),
    sa.Column('tkbb_member', sa.Boolean(), nullable=False),
    sa.Column('data_status', sa.Text(), nullable=False),
    sa.Column('brand_color', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("bddk_status IN ('active', 'pre_launch')", name=op.f('ck_banks_bddk_status_valid')),
    sa.CheckConstraint("data_status IN ('rich', 'limited', 'none')", name=op.f('ck_banks_data_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_banks'))
    )
    with op.batch_alter_table('banks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_banks_code'), ['code'], unique=True)

    op.create_table('glossary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.Text(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('conventional_equivalent', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('is_forbidden_conventional', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_glossary'))
    )
    with op.batch_alter_table('glossary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_glossary_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_glossary_is_forbidden_conventional'), ['is_forbidden_conventional'], unique=False)
        batch_op.create_index(batch_op.f('ix_glossary_term'), ['term'], unique=True)

    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('urls_discovered', sa.Integer(), nullable=False),
    sa.Column('urls_fetched', sa.Integer(), nullable=False),
    sa.Column('campaigns_new', sa.Integer(), nullable=False),
    sa.Column('campaigns_updated', sa.Integer(), nullable=False),
    sa.Column('errors_count', sa.Integer(), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('scraper_version', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('running', 'success', 'partial', 'failed')", name=op.f('ck_scrape_runs_status_valid')),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], name=op.f('fk_scrape_runs_bank_id_banks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scrape_runs'))
    )
    with op.batch_alter_table('scrape_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scrape_runs_bank_id'), ['bank_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scrape_runs_status'), ['status'], unique=False)

    op.create_table('source_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=True),
    sa.Column('url_hash', sa.Text(), nullable=False),
    sa.Column('doc_type', sa.Text(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_type', sa.Text(), nullable=True),
    sa.Column('raw_html_path', sa.Text(), nullable=True),
    sa.Column('raw_html_sha256', sa.Text(), nullable=True),
    sa.Column('clean_text', sa.Text(), nullable=True),
    sa.Column('clean_text_sha256', sa.Text(), nullable=True),
    sa.Column('scraper_name', sa.Text(), nullable=True),
    sa.Column('scraper_version', sa.Text(), nullable=True),
    sa.Column('robots_allowed', sa.Boolean(), nullable=False),
    sa.Column('is_soft_404', sa.Boolean(), nullable=False),
    sa.Column('discovery_method', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("doc_type IN ('campaign', 'product', 'rate_table', 'listing', 'other')", name=op.f('ck_source_documents_doc_type_valid')),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], name=op.f('fk_source_documents_bank_id_banks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_documents'))
    )
    with op.batch_alter_table('source_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_documents_bank_id'), ['bank_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_documents_clean_text_sha256'), ['clean_text_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_documents_url_hash'), ['url_hash'], unique=False)

    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('external_slug', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('summary_ai', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('category_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('segment', sa.Text(), nullable=True),
    sa.Column('target_customer', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('date_precision', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('participation_channel', sa.Text(), nullable=True),
    sa.Column('participation_method', sa.Text(), nullable=True),
    sa.Column('sms_keyword', sa.Text(), nullable=True),
    sa.Column('sms_number', sa.Text(), nullable=True),
    sa.Column('coupon_code', sa.Text(), nullable=True),
    sa.Column('conditions_text', sa.Text(), nullable=True),
    sa.Column('exclusions_text', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("date_precision IN ('exact', 'partial', 'inferred', 'unknown')", name=op.f('ck_campaigns_date_precision_valid')),
    sa.CheckConstraint("status IN ('active', 'upcoming', 'expired', 'unknown')", name=op.f('ck_campaigns_status_valid')),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], name=op.f('fk_campaigns_bank_id_banks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], name=op.f('fk_campaigns_source_document_id_source_documents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns')),
    sa.UniqueConstraint('bank_id', 'external_slug', name='uq_campaigns_bank_id_external_slug')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_bank_id'), ['bank_id'], unique=False)
        batch_op.create_index('ix_campaigns_bank_id_status', ['bank_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_category'), ['category'], unique=False)
        batch_op.create_index('ix_campaigns_end_date', ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_segment'), ['segment'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_status'), ['status'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('product_type', sa.Text(), nullable=True),
    sa.Column('segment', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], name=op.f('fk_products_bank_id_banks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], name=op.f('fk_products_source_document_id_source_documents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_bank_id'), ['bank_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_product_type'), ['product_type'], unique=False)

    op.create_table('campaign_extractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.Text(), nullable=False),
    sa.Column('value_raw', sa.Text(), nullable=True),
    sa.Column('value_normalized', sa.Text(), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('evidence_char_start', sa.Integer(), nullable=True),
    sa.Column('evidence_char_end', sa.Integer(), nullable=True),
    sa.Column('evidence_source_url', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('extraction_method', sa.Text(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=True),
    sa.Column('model_version', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.Text(), nullable=True),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('validation_note', sa.Text(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("extraction_method IN ('table', 'rule', 'llm', 'hybrid')", name=op.f('ck_campaign_extractions_extraction_method_valid')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_campaign_extractions_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_extractions'))
    )
    with op.batch_alter_table('campaign_extractions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_extractions_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_extractions_field_name'), ['field_name'], unique=False)

    op.create_table('campaign_metrics',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('profit_rate_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('profit_share_rate_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('term_months_min', sa.Integer(), nullable=True),
    sa.Column('term_months_max', sa.Integer(), nullable=True),
    sa.Column('installment_count', sa.Integer(), nullable=True),
    sa.Column('financing_amount_min', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('financing_amount_max', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('min_spend_try', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('max_spend_try', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('reward_amount_try', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('reward_type', sa.Text(), nullable=True),
    sa.Column('cashback_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('discount_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('loyalty_points', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('allocation_fee_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('file_fee_try', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('has_no_fee', sa.Boolean(), nullable=True),
    sa.Column('appraisal_fee_covered', sa.Boolean(), nullable=True),
    sa.Column('max_total_benefit_try', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('tier_structure', sa.JSON(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_campaign_metrics_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('campaign_id', name=op.f('pk_campaign_metrics'))
    )
    op.create_table('product_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('term_months', sa.Integer(), nullable=True),
    sa.Column('profit_rate_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('allocation_fee_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('monthly_cost_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('annual_cost_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('variant', sa.Text(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_rates_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_rates'))
    )
    with op.batch_alter_table('product_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_rates_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Şemayı geri al."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_rates_product_id'))

    op.drop_table('product_rates')
    op.drop_table('campaign_metrics')
    with op.batch_alter_table('campaign_extractions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_extractions_field_name'))
        batch_op.drop_index(batch_op.f('ix_campaign_extractions_campaign_id'))

    op.drop_table('campaign_extractions')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_product_type'))
        batch_op.drop_index(batch_op.f('ix_products_bank_id'))

    op.drop_table('products')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_status'))
        batch_op.drop_index(batch_op.f('ix_campaigns_segment'))
        batch_op.drop_index('ix_campaigns_end_date')
        batch_op.drop_index(batch_op.f('ix_campaigns_category'))
        batch_op.drop_index('ix_campaigns_bank_id_status')
        batch_op.drop_index(batch_op.f('ix_campaigns_bank_id'))

    op.drop_table('campaigns')
    with op.batch_alter_table('source_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_documents_url_hash'))
        batch_op.drop_index(batch_op.f('ix_source_documents_clean_text_sha256'))
        batch_op.drop_index(batch_op.f('ix_source_documents_bank_id'))

    op.drop_table('source_documents')
    with op.batch_alter_table('scrape_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scrape_runs_status'))
        batch_op.drop_index(batch_op.f('ix_scrape_runs_bank_id'))

    op.drop_table('scrape_runs')
    with op.batch_alter_table('glossary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_glossary_term'))
        batch_op.drop_index(batch_op.f('ix_glossary_is_forbidden_conventional'))
        batch_op.drop_index(batch_op.f('ix_glossary_category'))

    op.drop_table('glossary')
    with op.batch_alter_table('banks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_banks_code'))

    op.drop_table('banks')
    # ### end Alembic commands ###
